language: node_js
node_js:
 - "8.10.0"
 before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 deploy:
    provider: heroku
    api_key:
     secure: "ae835325-02ed-4aa7-a21d-01766ef5437c"
